version: '3'

# requires a network loadbancer to expose neo4j ports
x-aws-loadbalancer: "arn:aws:elasticloadbalancing:us-east-2:513084038389:loadbalancer/net/ryp-lb2/6f8257976df59550"

services:
    ryp-legacy:
      image: jarrah/ryp:legacy
      build: 
        context: ./legacy/
      networks:
        - ryp-net
    ryp-api:
      image: jarrah/ryp:api
      build: 
        context: ./api/
      volumes:
        - ryp-data:/opt/data
      networks:
        - ryp-net
      depends_on: 
        - ryp-neo4j
    ryp-create:
      image: jarrah/ryp:create
      build: 
        context: ./create/
        args:
          - BASE_HREF=${BASE_HREF:-/ryp}/create/
      networks:
        - ryp-net
      depends_on: 
        - ryp-api
    ryp-chat:
      image: jarrah/ryp:chat
      build: 
        context: ./chat/
        args:
          - BASE_HREF=${BASE_HREF:-/ryp}/chat/
      networks:
        - ryp-net
      depends_on: 
        - ryp-api
    ryp-inspect:
      image: jarrah/ryp:inspect
      build: 
        context: ./inspect/
        args:
          - BASE_HREF=${BASE_HREF:-/ryp}/inspect/
      networks:
        - ryp-net
      depends_on: 
        - ryp-api
    ryp-neo4j: 
      image: neo4j:3.5
      # Remove comments to reach Neo4j GUI from localhost
      ports:
      # HOST_PORT:CONTAINER_PORT
        - "127.0.0.1:7474:7474"
        - "127.0.0.1:7687:7687"
      volumes:
        - ryp-db:/data
      networks:
        - ryp-net      
      environment:
        NEO4J_AUTH: "neo4j/coney"
    ryp-reverse:
      image: jarrah/ryp:reverse
      build:
        context: ./reverse/
      # Unique access point to all components
      ports:
        - 80:80
        - 443:443
      networks:
        - ryp-net
      depends_on: 
        - ryp-api
        - ryp-inspect
        - ryp-create
        - ryp-chat
        - ryp-legacy
networks:
  ryp-net:
    driver: bridge

volumes:
  ryp-data:
  ryp-db:

# required to configure load balancer to redirect 80 -> 443
x-aws-cloudformation:
  Resources:
    RypreverseTCP80Listener:
      Properties:
        # Implement the redirect to HTTPS
        DefaultActions:
        - Type: redirect
          RedirectConfig:
            Port: 443
            Protocol: HTTPS
            StatusCode: HTTP_301
    RypreverseTCP443Listener:
      Properties:
        Protocol: "HTTPS"
        Certificates:
          - arn:aws:acm:us-east-2:513084038389:certificate/eac2dd0d-8356-425b-9769-674f8d6d4e95
        DefaultActions:
          - Type: "fixed-response"
            FixedResponseConfig:
              ContentType: "text/plain"
              MessageBody: "BAD DOMAIN NAME"
              StatusCode: "200"
    # Delete port 443 target group
    RypreverseTCP443TargetGroup:
    # Match www.DOMAIN and redirect to DOMAIN
    RypreverseTCP443WWWRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        ListenerArn:
          Ref: RypreverseTCP443Listener
        Priority: 50000
        Conditions:
          - Field: host-header
            HostHeaderConfig:
              Values:
                - www.rateyourproject.org
        Actions:
          - Type: redirect
            RedirectConfig:
              Host: rateyourproject.org
              Port: 443
              Protocol: HTTPS
              StatusCode: HTTP_301
    # Match DOMAIN and forward to the port 80 Target Group
    RypreverseTCP443BaseRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        ListenerArn:
          Ref: RypreverseTCP443Listener
        Priority: 40000
        Conditions:
          - Field: host-header
            HostHeaderConfig:
              Values:
                - rateyourproject.org
        Actions:
          - Type: forward
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: RypreverseTCP80TargetGroup
    RypreverseService:
      Properties:
        # Eliminate the reference to RypreverseTCP80TargetGroup
        LoadBalancers:
        - ContainerName: ryp-reverse
          ContainerPort: 80
          TargetGroupArn:
            Ref: RypreverseTCP80TargetGroup

